- job_name: blackbox_https_srini23
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
        - https://srini23.com
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      name: additional-scrape-configs
      key: additional-scrape-configs.yaml
