apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-v2
  namespace: nginx-bg
  annotations:
    kubernetes.io/ingress.allow-http: "true"
spec:
  ingressClassName: gce
  rules:
  - host: srini23.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-svc
            port:
              number: 80
