apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-v2
  namespace: nginx-bg
  annotations:
    networking.gke.io/managed-certificates: "nginx-cert"
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.allow-https-redirect: "true"
spec:
  ingressClassName: gce-17-glb
  rules:
  - host: srini23.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-svc
            port:
              number: 80
